### ISSUE TITLE
Mehr ordnung

### ISSUE THREAD

**Issue by ljonka07** [ProjektWoche/Gruppe2#13]
So, hier eine idee von mir, um die übersichtlichkeit und das debuggen zu erleichtern:
eine main-datei, die den einzelnen stages, die als funktionen aufgerufen werden, ohne, dass sie von sich aus cross-funktional aktiv werden, das fenster übergibt, das dann mit einem pane bestückt wird, welches dann am ende löscht und ein void zurückgibt (bzw. im falle des Spiel-(bzw. Settings-)Fensters gewonnen/verloren (bzw. 1/2 Spieler))

etwa so:
main datei ruft "Start-Fenster" auf
"Start-Fenster" ist fertig, gibt nichts zurück, wird als start-button-gedrückt interpretiert
main-datei ruft "Settings-Fenster" auf
Settings-Fenster gibt 1/2 Spieler zurück
main-datei ruft "Spiel-Fenster" auf
"Spiel-Fenster" gibt gewonnen/verloren zurück
main-datei ruft "Gewonnen/Verloren-Fenster" auf
Ende

das ist bisher nur ein Grundgerüst...
Das umstellen würde dann ich übernehmen

**Comment by BB20101997** [comment]
ich glaub mir wird die Absicht welche du verfolgst nicht ganz klar könntest du das noch mal etwas klarer formulieren ?
sorry für die späte antwort

**Comment by BB20101997** [comment]
Wir könnten das sonst am besten in einem Gespräch z.B. über Skype klaren ist meist einfacher als per Nachrichten, vor allem bei den verzögerungen zwischen antworten

**Comment by ljonka07** [comment]
die verzögerung wird immer größer :)
jetzt brauche ich nur noch die skype-namen von dir und lukas, dann können wir das dort klären
meiner ist philipp.herzog007

**Comment by BB20101997** [comment]
ich schließe das hier mal weil es erledigt scheint
